# Generated by Django 5.0.7 on 2024-07-25 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='library',
            fields=[
                ('book_id', models.AutoField(primary_key=True, serialize=False)),
                ('book_title', models.CharField(max_length=50)),
                ('book_desc', models.CharField(max_length=250)),
                ('book_date', models.DateField()),
            ],
            options={
                'db_table': 'libraryTable',
            },
        ),
    ]
